// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijDyZpaIbvmdpfz8e106dcKGC20L-kDM',
    appId: '1:18020754221:android:7bf1004c9c073a3643a9a4',
    messagingSenderId: '18020754221',
    projectId: 'emotijournal-39968',
    storageBucket: 'emotijournal-39968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYTZ2I6yPScJLsq6NWpRxZGoDbW3xEe1U',
    appId: '1:18020754221:ios:09721bbb33a745f443a9a4',
    messagingSenderId: '18020754221',
    projectId: 'emotijournal-39968',
    storageBucket: 'emotijournal-39968.firebasestorage.app',
    androidClientId: '18020754221-lgdm5f0pnhgg711e5rv6eij7290hc6mb.apps.googleusercontent.com',
    iosClientId: '18020754221-jc0f7er0fa5dg0j5q8lv4ktv7nljd0kk.apps.googleusercontent.com',
    iosBundleId: 'com.app.emotijournal',
  );
}
